### ISSUE TITLE
RFC: repo-level config, per-category `nav`

### ISSUE THREAD

**Issue by CodyJasonBennett** [pmndrs/docs#230]
Continues #217.

This project is quite hidden, based on the docs branch. I'd suggest eventually moving that branch to its own repo and optionally reading open graph config from libraries' repositories.

```js
// docs.config.json
{
  // Directory to look for docs, defaults to repo root
  // "root": "docs",
  
  // OpenGraph meta
  "title": "React Three Fiber",
  "description": "React-three-fiber is a React renderer for three.js",
  "image": "docs/social-image.jpg",

  // Order categories by pathname, `nav` frontmatter will control page order per category
  categories: [
    "introduction",
    "getting-started"
  ]
}
```

We can substitute local, hard-coded config in this repo with a NPM-like repository path:

```js
// data/libraries.ts
'react-three-fiber': 'pmndrs/react-three-fiber/master/docs.config.json',
```

**Comment by CodyJasonBennett** [comment]
Curious if we can substitute some of the open graph meta with those from GitHub. Would be nice to point to a repo and have the site find `docs.config.json` in addition to repo meta.

```js
// data/libraries.ts
'react-three-fiber': 'pmndrs/react-three-fiber',
```

**Comment by abernier** [comment]
the repo has been renamed to pmndrs/docs and `main` is now the production branch deployed on vercel
