### ISSUE TITLE
[docs/zustand] Question marks in links removed in Github, not docs

### ISSUE THREAD

**Issue by chrisk-7777** [pmndrs/docs#259]
Hey 👋 

A PR was raised on Zustand docs (https://github.com/pmndrs/zustand/pull/1398), and an interesting tidbit came up. 
When it comes to a "?" in a documentation title/subtitle, Github (I believe incorrectly) strips them. Whereas this project (correctly) keeps them. 

For context, one of the goals of the Zustand docs is for the docs and links to work across both Github and the docs site. I don't know if the same applies to the other pmndrs projects. 

The example from the PR is:

```
See [How can I check if my store has been hydrated?](#how-can-i-check-if-my-store-has-been-hydrated?)
```

If the user is viewing the md in Github it won't correctly link to the right spot on the page (because the ? is stripped in the final output). If the user is viewing the page on the docs site it works correctly. 

However, if we go the other way:

```
See [How can I check if my store has been hydrated?](#how-can-i-check-if-my-store-has-been-hydrated)
```
It will work in Github but not the docs site. 

Before I raise a PR @CodyJasonBennett I wanted to get your input. What would you leans towards?

 - Stripping the "?" within the docs to align with Github? 
 - Leave it as a known limitation with GH? 
 - Other?

**Comment by CodyJasonBennett** [comment]
I would prefer if we could have section links on the site be forgiving to cases like this. We can then align with GitHub without consequence.

**Comment by chrisk-7777** [comment]
Thanks Cody, I'll get a PR organised so section links align with GH
