### ISSUE TITLE
Drei documentation contols introduction unclear

### ISSUE THREAD

**Issue by theRealProHacker** [pmndrs/docs#276]
It is not clear to me where the `useResource` comes from. Which library exports it? How can it be accessed/imported?

https://dext.vercel.app/drei/controls/introduction

```js
const myCamera = useResource()

return (
  <>
    <PerspectiveCamera ref={myCamera} position={[0, 5, 5]} />
    <OrbitControls camera={myCamera.current} />
  </>
)

```

**Comment by abernier** [comment]
I'm late to this, but seems outdated, at least the link does not work anymore
