### ISSUE TITLE
aria

### ISSUE THREAD

**Issue by abernier** [pmndrs/docs#291]
integrate radix primitives into components for keyboard navigation

**Comment by dbritto-dev** [comment]
@abernier I'd use `react-aria-components` instead of `radix`

**Comment by abernier** [comment]
why rac over radix-primitives ?

**Comment by dbritto-dev** [comment]
@abernier `radix-ui` hard to test sometimes, composition is a bit tricky in some cases, `react-aria`/`react-aria-components` better composition and accesibility 

- https://argos-ci.com/blog/react-aria-migration
- https://syntax.fm/show/751/ui-components-shadcn-tailwind-ui-headless-react-aria-radix-ui

**Comment by abernier** [comment]
did you used them both already?

**Comment by abernier** [comment]
although I'm considering RAC for search... (which radix-primitives does not seem to have components for)

**Comment by dbritto-dev** [comment]
@abernier I've used both

**Comment by abernier** [comment]
wip https://github.com/pmndrs/docs/pull/329
