### ISSUE TITLE
GitHub Logo

### ISSUE THREAD

**Issue by Fedox-die-Ente** [pmndrs/docs#357]
![image](https://github.com/user-attachments/assets/e215eafc-bdad-4f1c-8c8d-02c3d3c4aaf8)

The github logo at the top right in the documentation needs an update, only the one with the circle is allowed.

See: https://github.com/logos

**Comment by abernier** [comment]
didn't understand, can you clarify?

**Comment by Fedox-die-Ente** [comment]
The GitHub logo that is currently used is not in the GitHub brand guidelines as usable, it could potentially cause legal issues if used. (As far as I know)

You should use one of the two logos available on the brand page 

![image](https://github.com/user-attachments/assets/fd6e0da2-021a-4bef-974a-5411ef756ef8)

**Comment by abernier** [comment]
can you PR this?

**Comment by Fedox-die-Ente** [comment]
Sure
